[[tls.certificates]]
certFile = "/etc/ssl/opcode.ovh.crt"
keyFile = "/etc/ssl/opcode.ovh.key"
stores = ["default"]

[tls.stores]
[tls.stores.default]
[tls.stores.default.defaultCertificate]
certFile = "/etc/ssl/opcode.ovh.crt"
keyFile = "/etc/ssl/opcode.ovh.key"
